env:
  global:
      env:
      - REPO_DIR="cftime"
      - BUILD_COMMIT=v1.2.1rel
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - NP_BUILD_DEP="numpy==1.17.3"
      - NP_TEST_DEP="numpy==1.17.3"
      # travis encrypt -r MacPython/cftime-wheels --org GITHUB_API_TOKEN="<github personal token>"
      - secure: "DpgZ/hgcbMWXPjoVsvfyYOUIbOcqPFrvbSd2BvnrGYg2T26tR+vV3AqHrGIYnUPlxtDy1zqskdu0f4gt4/h9JJMQbIDQn0yBZs2ok6zt0zZIjaEEMPmd5hkhVE6b8ENRNHoEmsHJKAjv1/2whnygQTvnarmknMpv4oY4Z3fTYyWRBedddbDBdmxNO3YBqSQPxCCkwSH2cjggktKBQPUOKEK6PjA31iTmyjpX5N+OWCLW7kn2PWJgqtfHcXRqKO4HP7ClmGGTNHIVsKW2sR3Zo5c+3PlRuPwaL9RBEfR0j12tvh1O+Rm/tycJ4i3E1gj1zvLL3+M23Mr1lHzXfPth6wXXB2acNvalEOI/pHev/Kejl31yw3/piGqYUJImGYALWVzTD8exP/Rbr1N113p+kP9BP4Ol4MN7O5auzooZ/iWYLvZwD1W4SmVRNrQT5JFLxRP2k9fTmwMiQJY64Yy0QI7aKaCfRjRY006rRSlpEo1GPNQBG+5PjtBodm9e7UQyfu7aRy5TA0LqsWahXj7JVhQ7HxhBlWz2t+cJnLHeTgRWjqws184jnNrwQ+v8vmV1vU4EWxr59Xn4j0Oi1n03K3KEp68SaQqq2zQ8JNrhktn412juUunKNEEsLjLKnkr5rR324e1CRQFWRd9FnbVOwyHar8XJL3ZTQKWnJ2sd0LU="

language: python
# Default Python version
python: 3.5
sudo: required
dist: trusty
services: docker

#matrix:
#  exclude:
#      # Exclude the default Python 3.5 build
#      - python: 3.5
jobs:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - NP_BUILD_DEP="numpy==1.17.3"
        - NP_TEST_DEP="numpy==1.17.3"
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
        - NP_BUILD_DEP="numpy==1.17.3"
        - NP_TEST_DEP="numpy==1.17.3"
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - NP_BUILD_DEP=numpy==1.17.3
        - NP_TEST_DEP=numpy==1.17.3
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
        - NP_BUILD_DEP=numpy==1.17.3
        - NP_TEST_DEP=numpy==1.17.3
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.9
        - NP_BUILD_DEP=numpy==1.19.4
        - NP_TEST_DEP=numpy==1.19.4
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.9
        - PLAT=i686
        - NP_BUILD_DEP=numpy==1.19.4
        - NP_TEST_DEP=numpy==1.19.4
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
        - MB_PYTHON_OSX_VER=10.9
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_PYTHON_OSX_VER=10.9
        - NP_BUILD_DEP="numpy==1.17.3"
        - NP_TEST_DEP="numpy==1.17.3"
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.8
        - MB_PYTHON_OSX_VER=10.9
        - NP_BUILD_DEP=numpy==1.17.3
        - NP_TEST_DEP=numpy==1.17.3
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.9
        - MB_PYTHON_OSX_VER=10.9
        - NP_BUILD_DEP=numpy==1.19.4
        - NP_TEST_DEP=numpy==1.19.4

before_install:
    - echo "Building cftime-$BUILD_COMMIT"
    - BUILD_DEPENDS="$NP_BUILD_DEP Cython"
    - TEST_DEPENDS="$NP_TEST_DEP pytest pytest-cov"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

# upload to github
deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/wheelhouse/*.whl"
  skip_cleanup: true
  on:
    repo: MacPython/cftime-wheels
    tags: true
