# vim ft=yaml
# CI on Windows via appveyor
# Largely from:
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
#
# Builds version specified in BUILD_COMMIT variable
# To chose version to build, edit value of BUILD_COMMIT

os: Visual Studio 2015

environment:
    global:
      # Remember to edit .travis.yml too
      BUILD_COMMIT: v1.0.3rel
      WHEELHOUSE_UPLOADER_USERNAME: travis-worker
      # 9s0gdDGnNnTt7hvyNpn0/ZzOMGPdwPp2SewFTfGzYk7uI+rdAN9rFq2D1gAP4NQh
      WHEELHOUSE_UPLOADER_SECRET:
        secure:
            "jBM5bVlciv3VGGBhhilljF5UlPVlsSDdody9CSSM7FMbX14EKzLFnGwQCsRRHUtGKVTjveT+u6I4Vq6ieEc6D21EUSU99mmN7Z0FnD6D0FMdmPsH8Eb8m6YvMlF7ypYqDS05awCiiU4QiYix4jv0I0oPaVTRz+1jW/1niZNlIb9pwyJwv7YuiIfpSuG084gkTNjkWhjE2jTJD0KyJ0n+PL3DT+a6AFsU7Y84RhgR/Nc/fPu1mcxcn4zJCdzP6isuQz+1AgrPKxnCqyphynFe9pRx7tp7v7+lNzkMozI5EVaYrGrVEfMIeuhFiCBhMjPpzlxxE4Gn/dCcz1xi8dkLUSYbq0Enf78lcbMurky5zP45sfFOtWBMUuj4WNhjL2C3S5bfgmJ7/OG9zJOLRbLZm8L4pMMNkUxsXsuq5wacgk9n3tajv1MVqdOhg101YrUsqP7LCAsDSSTQOI3c8m2CKLtKeg1kv26ONUnfTODrc53ABtfFr4kuDtrD/lRkRxC+IfgFPzGkkuZbmnr3zwkCPYOhvYCAwS2aDAImNHDJmyYW23ujodMPnU+4KLupiT19EDNgWl0Zu1wh0Vmb0t6aLKGpCfMSA+n6tY+kHX6gdG8CW5K1h/c4OD4szkWDWtAi6z2NXYvwyT0w+6UBDEK1t8ucMhhsYKhSz8CkrS2DfA4="

    matrix:
    - PYTHON: C:\Python37
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python35
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64

install:
  - cmd: echo "Using cmd"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # Fix MSVC builds for 64-bit Python
  # See
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  - python -m pip install --upgrade pip
  # Pin wheel to 0.26 to avoid Windows ABI tag for built wheel
  - pip install wheel==0.26
  - git submodule update --init
  # Dependencies for package
  - pip install Cython

build_script:
  # Build and install the wheel
  - cd cftime
  - git fetch origin
  - git checkout %BUILD_COMMIT%
  - python setup.py bdist_wheel
  - ps: |
      # Upload artifact to Appveyor immediately after build
      ls dist -r | Foreach-Object {
          appveyor PushArtifact $_.FullName
          pip install $_.FullName
      }
  - cd dist
  - pip install --pre --no-index -f . cftime
  - cd ..

test_script:
  # Run some tests
  - mkdir tmp
  - cd tmp
  - pip install pytest pytest-cov
  - pytest -v ../test/test_cftime.py
  - cd ..

after_test:
  # If tests are successful, create binary packages for the project.
  - dir dist

on_success:
  # Upload the generated wheel package to Rackspace
  # On Windows, Apache Libcloud cannot find a standard CA cert bundle so we
  # disable the ssl checks.
  - pip install wheelhouse-uploader
  - python -m wheelhouse_uploader upload
    --local-folder=dist --no-update-index
    wheels
