# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and upload wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:
#  schedule:
#    - cron: '0 0 * * 0,3' # 2/weekly

jobs:

  build_aarch64:

    name: "build (${{ matrix.pyver }}, aarch64)"
    strategy:
      matrix:
        pyver: [cp37-cp37m, cp38-cp38, cp39-cp39]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64
      python-version: ${{ matrix.pyver }}
      BUILD_COMMIT: v1.5.0rel
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Build and Test
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc 'yum install -y wget && \
          echo "Set Up Conda Env" && \
          wget https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-aarch64.sh -O miniconda.sh && \
          export MINICONDA_PATH=/root/miniconda && \
          chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH && \
          export PATH=$MINICONDA_PATH/bin:$PATH && \
          export Python=${{ env.python-version }} && \
          git clone https://github.com/Unidata/cftime && \
          git checkout $BUILD_COMMIT && \
          cd cftime && \
          conda create --name TEST python=${Python:2:1}.${Python:3:1} --file requirements.txt --file requirements-dev.txt && \
          source activate TEST && \
          pip install -v -e  . --no-deps --force-reinstall && \
          conda info --all && \
          conda list && \
          py.test -vv test && \
          python setup.py --version && \
          pip wheel . -w dist --no-deps && \
          check-manifest --verbose && \
          pip install readme-renderer && \
          twine check dist/* && \
          mkdir -p ${{ github.workspace }}/wheelhouse && \
          ls -l dist && \
          CONTAINER_ID=$(docker ps -alq) && \
          FILE=$(docker exec $CONTAINER_ID sh -c "ls dist/*whl") && \
          docker cp $CONTAINER_ID:dist/$FILE ${{ github.workspace }} && \
          conda deactivate'

    - name: Check Wheel
      run: |
        ls -l ${{ github.workspace }}

    - name: Upload wheels to release
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'create'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/cftime*whl
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  build_macos_linux:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:

      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: [ubuntu-latest, macos-latest]
        platform: [x64, x32]
        MB_ML_VER: [1,2014]
        exclude:
          - os: macos-latest  
            platform: x32
    env:
      BUILD_COMMIT: v1.5.0rel
      REPO_DIR: cftime
      PKG_NAME: cftime
      UNICODE_WIDTH: 32
      MB_PYTHON_VERSION: ${{ matrix.python-version }}
      TRAVIS_PYTHON_VERSION: ${{ matrix.python-version }}
      MB_ML_VER: ${{ matrix.MB_ML_VER }}
      TRAVIS_REPO_SLUG: ${{ github.repository }}
      TRAVIS_BRANCH: ${{ github.head_ref }}
      TRAVIS_PULL_REQUEST: ${{ github.event.number }}
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
      MULTIBUILD_WHEELS_STAGING_ACCESS: ${{ secrets.MULTIBUILD_WHEELS_STAGING_ACCESS }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pin Numpy version
      run: |
        if [ "$MB_PYTHON_VERSION" == '3.6' ]; then
          echo "NP_BUILD_DEP=$(echo numpy==1.17.3)" >> $GITHUB_ENV;
          echo "NP_TEST_DEP=$(echo numpy==1.17.3)" >> $GITHUB_ENV;
        elif [ "$MB_PYTHON_VERSION" == '3.7' ]; then
          echo "NP_BUILD_DEP=$(echo numpy==1.17.3)" >> $GITHUB_ENV;
          echo "NP_TEST_DEP=$(echo numpy==1.17.3)" >> $GITHUB_ENV;
        elif [ "$MB_PYTHON_VERSION" == '3.8' ]; then
          echo "NP_BUILD_DEP=$(echo numpy==1.17.3)" >> $GITHUB_ENV;
          echo "NP_TEST_DEP=$(echo numpy==1.17.3)" >> $GITHUB_ENV;
        elif [ "$MB_PYTHON_VERSION" == '3.9' ]; then
          echo "NP_BUILD_DEP=$(echo numpy==1.19.4)" >> $GITHUB_ENV;
          echo "NP_TEST_DEP=$(echo numpy==1.19.4)" >> $GITHUB_ENV;
        else
          echo "None of the defined python version, use default"
        fi
    - name: Setup Environment variables
      run: |
        if [ "schedule" == "${{ github.event_name }}" ] || [ "master" == "$BUILD_COMMIT" ]; then echo "TOKEN=$SCIPY_WHEELS_NIGHTLY_ACCESS" >> $GITHUB_ENV; else echo "TOKEN=$MULTIBUILD_WHEELS_STAGING_ACCESS" >> $GITHUB_ENV; fi
        if [ "x32" == "${{ matrix.platform }}" ]; then echo "PLAT=i686" >> $GITHUB_ENV; else echo "PLAT=x86_64" >> $GITHUB_ENV; fi
        if [ "macos-latest" == "${{ matrix.os }}" ]; then echo "TRAVIS_OS_NAME=osx" >> $GITHUB_ENV; else echo "TRAVIS_OS_NAME=${{ matrix.os }}" >> $GITHUB_ENV; fi
        if [ "schedule" == "${{ github.event_name }}" ]; then echo "TRAVIS_EVENT_TYPE=cron" >> $GITHUB_ENV; else echo "TRAVIS_EVENT_TYPE=${{ github.event_name }}" >> $GITHUB_ENV; fi
        if [ "schedule" == "${{ github.event_name }}" ]; then echo "BUILD_COMMIT=master" >> $GITHUB_ENV; else echo "BUILD_COMMIT=$BUILD_COMMIT" >> $GITHUB_ENV; fi
    - name: Setup Special Environment variables for Linux
      if: startsWith(matrix.os,'ubuntu') && matrix.MB_ML_VER == 2010
      run: |
        echo "DOCKER_TEST_IMAGE=$(echo multibuild/xenial_$PLAT)" >> $GITHUB_ENV
    - name: Print some Environment variable
      run: |
        echo "TRAVIS_BRANCH: ${TRAVIS_BRANCH}"
        echo "TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}"
        echo "TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}"
        echo "TRAVIS_EVENT_TYPE: ${TRAVIS_EVENT_TYPE}"
        echo "TRAVIS_OS_NAME: ${TRAVIS_OS_NAME}"
        echo "PLAT: ${PLAT}"
        echo "DOCKER_TEST_IMAGE: ${DOCKER_TEST_IMAGE}"

    - name: Install VirtualEnv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
    - name: Build and Install Wheels
      run: |
        BUILD_DEPENDS="$NP_BUILD_DEP cython"
        TEST_DEPENDS="$NP_TEST_DEP pytest pytest-cov"
        source multibuild/common_utils.sh
        source multibuild/travis_steps.sh
        echo "------- BEFORE INSTALL --------"
        before_install
        echo "------- CLEAN CODE --------"
        clean_code $REPO_DIR $BUILD_COMMIT
        echo "------- BUILD WHEEL --------"
        build_wheel $REPO_DIR $PLAT
        echo "------- INSTALL_RUN --------"
        install_run $PLAT
        ls -l wheelhouse/cftime*whl
    - name: Upload wheels to release
      uses: svenstaro/upload-release-action@v2
      if: github.event_name == 'create'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.workspace }}/wheelhouse/cftime*whl
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
